server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ http://elasticsearch:9200 ]


## Security credentials
#
elasticsearch.username: ${KIBANA_USER}
elasticsearch.password: ${KIBANA_PASSWORD}